Algoritmo "fatorial"
// Fazer um programa para ler um número natural N (valor máximo: 15),
// e depois calcular e mostrar o fatorial de N.
Var

   n, fatorial, i: inteiro


Inicio

      fatorial <- 1
      
      escreva("Digite o valor de N: ")
      leia(n)
      
      para i de 1 ate n faca
      
           fatorial <- fatorial * i
           i <- i + 1

      fimpara
      

      escreval(fatorial)



Fimalgoritmo